param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host "OpenCycle Play Console upload helper"
Write-Host ""
Write-Host "This helper prints owner-side Play upload steps only. It does not read, print, prompt for, upload, or store Play Console credentials, service-account JSON, keystores, keystore passwords, signed AAB files, Cloudflare tokens, or GitHub tokens."
Write-Host ""
Write-Host "Signed AAB expected path: apps/mobile/android/app/build/outputs/bundle/release/app-release-signed.aab"
Write-Host "Primary privacy URL after domain validation: https://open-cycle.com/privacy"
Write-Host "Temporary privacy URL before custom-domain validation: https://open-cycle-site.pages.dev/privacy"
Write-Host ""
Write-Host "1. Confirm public and private release gates before upload:"
Write-Host "npm run release:next"
Write-Host "npm run validate:custom-domain:live"
Write-Host "npm run validate:github:live"
Write-Host "npm run validate:github:actions"
Write-Host "npm run validate:play-store-private-ready"
Write-Host ""
Write-Host "2. Confirm the signed candidate evidence and runtime QA are complete:"
Write-Host "npm run mobile:signed-aab:evidence -- --require-signed"
Write-Host "npm run mobile:signed-aab:sync-evidence"
Write-Host "npm run validate:runtime-qa-report -- --require-complete"
Write-Host "Confirm reports/signed-aab-evidence.json records the current unsigned AAB SHA-256 and size; this proves the signed upload came from the current release build."
Write-Host ""
Write-Host "3. Use the public-safe Play packets while filling Play Console:"
Write-Host "npm run generate:play-console-packet"
Write-Host "npm run validate:play-console-packet"
Write-Host "npm run validate:play-app-content"
Write-Host "npm run validate:play-release-candidate"
Write-Host "npm run validate:play-production-readiness"
Write-Host ""
Write-Host "4. Upload the signed AAB manually in Play Console."
Write-Host "Do not commit or upload Play service-account JSON, tester email lists, screenshots with private account data, or signed artifacts to public GitHub."
Write-Host ""
Write-Host "5. Generate and fill the private upload confirmation after upload:"
Write-Host "npm run generate:play-upload-confirmation"
Write-Host "Keep signedAabSha256, signedAabSizeBytes, unsignedAabSha256, and unsignedAabSizeBytes matched to reports/signed-aab-evidence.json."
Write-Host "npm run validate:play-upload-confirmation -- --require-complete"
Write-Host ""
Write-Host "6. Run the final completion gate only after every external/private item is true:"
Write-Host "npm run validate:play-store-complete"
Write-Host ""
Write-Host "Reference docs:"
Write-Host "docs/play-store-release.md"
Write-Host "docs/release-owner-checklist.md"
Write-Host "docs/runtime-qa.md"
