param(
  [string]$Repo = "kborndorff/Open-Cycle",
  [string]$SourceRepo = "kborndorff/open-cycle-source",
  [string]$Branch = "main"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host "OpenCycle GitHub publication helper"
Write-Host ""
Write-Host "This helper prints owner-side publication commands only."
Write-Host "It does not run git, push code, read tokens, or set secrets."
Write-Host "Do not run the printed git commands until the owner explicitly approves publication."
Write-Host ""
Write-Host "Proof/product repository target: https://github.com/$Repo"
Write-Host "Full source repository target: https://github.com/$SourceRepo"
Write-Host "Branch target: $Branch"
Write-Host ""
Write-Host "Live validator note:"
Write-Host "- GitHub may display the repository with different casing, such as kborndorff/Open-Cycle."
Write-Host "- That is acceptable; publish this worktree to the default branch, then rerun the live validators."
Write-Host ""
Write-Host "Before publishing, run the public-safe local gates:"
Write-Host ""
Write-Host "npm run validate:release"
Write-Host "npm run validate:play-store-public"
Write-Host "npm run generate:public-repo-manifest"
Write-Host "npm run validate:public-repo-manifest"
Write-Host "npm run validate:public-push"
Write-Host "npm run generate:github-repository-bundles"
Write-Host "npm run validate:github-repository-bundles"
Write-Host "npm run package:github-repository-bundles"
Write-Host "npm run validate:github-repository-archives"
Write-Host "npm run release:handoff"
Write-Host ""
Write-Host "Publication split:"
Write-Host "- Push public proof, security, store-facing upload materials, and release evidence helpers to https://github.com/$Repo."
Write-Host "- Push the complete inspectable source tree to https://github.com/$SourceRepo."
Write-Host "- Keep signed AABs, keystores, Play credentials, tokens, private screenshots, and unredacted reports out of both repositories."
Write-Host ""
Write-Host "Validated ZIP upload fallback:"
Write-Host "- Upload dist/github-repositories/Open-Cycle.zip contents to https://github.com/$Repo."
Write-Host "- Upload dist/github-repositories/open-cycle-source.zip contents to https://github.com/$SourceRepo."
Write-Host "- Validate the ZIPs first with npm run validate:github-repository-archives."
Write-Host "- The ZIP report is reports/github-repository-archives.json."
Write-Host ""
Write-Host "validated public-safe GitHub bundles publisher:"
Write-Host "- Dry run: npm run github:publish-bundles:dry-run"
Write-Host "- Apply after owner approval and Git authentication: npm run github:publish-bundles:apply"
Write-Host "- Script: scripts/publish-github-repository-bundles.ps1"
Write-Host "- The dry run creates no commits and pushes nothing."
Write-Host ""
Write-Host "If Git is already initialized and this worktree is ready to publish to the proof/product repository, owner-side commands are:"
Write-Host ""
Write-Host "git status"
Write-Host "git remote -v"
Write-Host "git remote add origin https://github.com/$Repo.git"
Write-Host "git branch -M $Branch"
Write-Host "git push -u origin $Branch"
Write-Host ""
Write-Host "If origin already exists, use this instead of remote add:"
Write-Host ""
Write-Host "git remote set-url origin https://github.com/$Repo.git"
Write-Host "git push -u origin $Branch"
Write-Host ""
Write-Host "For the full source repository, use a separate clean clone or an explicit second remote:"
Write-Host ""
Write-Host "git remote add source https://github.com/$SourceRepo.git"
Write-Host "git push -u source $Branch"
Write-Host ""
Write-Host "If a source remote already exists:"
Write-Host ""
Write-Host "git remote set-url source https://github.com/$SourceRepo.git"
Write-Host "git push -u source $Branch"
Write-Host ""
Write-Host "After pushing and waiting for GitHub Actions:"
Write-Host ""
Write-Host "npm run validate:github:live"
Write-Host "npm run validate:github:actions"
Write-Host "npm run release:public-ready"
Write-Host ""
Write-Host "Cloudflare secrets still belong in GitHub Actions secrets, not in git or chat:"
Write-Host "Keep reports/, signed AAB files, keystores, Play service-account JSON, and tester lists out of GitHub."
Write-Host ""
Write-Host ""
Write-Host "npm run github:setup-deploy-secrets"
Write-Host ""
Write-Host "No secret values are printed by this helper."
