param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host "OpenCycle Android signing helper"
Write-Host ""
Write-Host "This helper prints owner-side signing steps only. It does not read, print, prompt for, or store keystore files, keystore passwords, key passwords, Play Console credentials, Cloudflare tokens, or GitHub tokens."
Write-Host ""
Write-Host "Unsigned AAB input: apps/mobile/android/app/build/outputs/bundle/release/app-release.aab"
Write-Host "Signed AAB output: apps/mobile/android/app/build/outputs/bundle/release/app-release-signed.aab"
Write-Host "Default private keystore location: `$HOME\.opencycle\keys\upload-keystore.jks"
Write-Host ""
Write-Host "1. Confirm non-secret signing prerequisites:"
Write-Host "npm run validate:signing-readiness"
Write-Host ""
Write-Host "2. Create an upload keystore only if you do not already have one:"
Write-Host "npm run mobile:create-upload-keystore -- -DryRun"
Write-Host "npm run mobile:create-upload-keystore"
Write-Host ""
Write-Host "3. Rehearse the private release flow without entering secrets:"
Write-Host "npm run mobile:release:android:prompted -- -DryRun"
Write-Host ""
Write-Host "4. Build and sign the Android App Bundle locally when ready:"
Write-Host "npm run mobile:release:android:prompted"
Write-Host ""
Write-Host "   If npm run validate:release already passed and the unsigned AAB above exists, sign the current bundle without rebuilding:"
Write-Host "npm run mobile:release:android:prompted -- -SkipBuild -SkipPublicGate"
Write-Host ""
Write-Host "5. Record private signed-AAB evidence after signing:"
Write-Host "npm run mobile:signed-aab:evidence -- --require-signed"
Write-Host "npm run mobile:signed-aab:sync-evidence"
Write-Host ""
Write-Host "6. Continue with signed runtime QA and Play upload confirmation:"
Write-Host "npm run validate:runtime-qa-report -- --require-complete"
Write-Host "npm run validate:play-upload-confirmation -- --require-complete"
Write-Host "npm run validate:play-store-private-ready"
Write-Host ""
Write-Host "Keep the upload keystore, passwords, signed AAB, completed private QA, and Play upload confirmation out of public GitHub."
Write-Host "Reference docs:"
Write-Host "docs/android-keystore-handling.md"
Write-Host "docs/mobile-release.md"
Write-Host "docs/release-owner-checklist.md"
