param()

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host "OpenCycle signed runtime QA helper"
Write-Host ""
Write-Host "This helper prints owner-side signed runtime QA steps only. It does not read, print, prompt for, upload, or store signed AAB files, device screenshots, tester notes, Play Console credentials, service-account JSON, keystores, keystore passwords, Cloudflare tokens, or GitHub tokens."
Write-Host ""
Write-Host "Private QA report: reports/runtime-qa-report.md"
Write-Host "Signed AAB evidence: reports/signed-aab-evidence.json"
Write-Host "Signed AAB path: apps/mobile/android/app/build/outputs/bundle/release/app-release-signed.aab"
Write-Host ""
Write-Host "1. Confirm the signed candidate exists and matches private evidence:"
Write-Host "npm run mobile:signed-aab:evidence -- --require-signed"
Write-Host "npm run mobile:signed-aab:sync-evidence"
Write-Host "npm run validate:android -- --require-signed"
Write-Host ""
Write-Host "2. Generate or refresh the private runtime QA template only when intended:"
Write-Host "npm run generate:runtime-qa-report"
Write-Host "npm run validate:runtime-qa-report"
Write-Host ""
Write-Host "3. Install the signed candidate through Play internal testing, bundletool, or Android Studio."
Write-Host "If adb or emulator is missing, install Android Studio SDK Platform Tools and Android Emulator, then reopen PowerShell so PATH refreshes."
Write-Host "Tooling check: npm run owner-tools:android-tooling-help"
Write-Host "Keep screenshots, tester identity, device notes, and signed artifacts out of public GitHub unless intentionally redacted."
Write-Host ""
Write-Host "4. Complete every checklist item in reports/runtime-qa-report.md:"
Write-Host "- airplane-mode launch"
Write-Host "- no login, account creation, network prompt, analytics, ads, crash reporting, push, or cloud sync"
Write-Host "- add, update, delete, persist, and clear all local cycle entries"
Write-Host "- no Internet, location, contact, media, notification, or backup surprises"
Write-Host "- optional Local Cycle links stay outside core local tracking"
Write-Host ""
Write-Host "5. Validate completion before Play upload:"
Write-Host "npm run validate:runtime-qa-report -- --require-complete"
Write-Host "npm run validate:play-store-private-ready"
Write-Host ""
Write-Host "Reference docs:"
Write-Host "docs/runtime-qa.md"
Write-Host "docs/release-owner-checklist.md"
Write-Host "docs/play-store-release.md"
